### ISSUE TITLE
Details that could be added to terraform/aws/README.md

### ISSUE THREAD

**Issue by danf425** [chef-cft/reference-pattern-aspdotnetcore#3]
Update the following so that the demo is easier to follow:

1)**Demoing the Environment as a Reference Pattern:**
-This will only run locally if you’ve pre-built a hart pkg, uploaded it to your origin, and promoted it to stable (Optionally, you could use  “devopslifter” as your origin name in the TF file)
-A Windows instance is needed in order to build it, upload it, and promote it to your own origin (plan.ps1)

2)**Line 18 spelling mistake:**
- Change “app” to “apply” in "Run terraform init Run terraform app"

**Comment by devopslifter** [comment]
README.md updated and merged
