### ISSUE TITLE
Specific Terraform version is needed.

### ISSUE THREAD

**Issue by danf425** [chef-cft/reference-pattern-aspdotnetcore#5]
Demo only runs if you use TF v11.14

My initial attempt was to run it on v11.11 which gave me an error.
I updated the TF to the latest version (v12.5), this also gave me an error.

I don't see anything being utilized that would make it specific to v11.14.
It might make sense to open it up to all v11

**Comment by devopslifter** [comment]
TF locked to version to prevent TF from adding something odd that breaks the demo. Agree that V11 should be safe - will look to get that added
